execute if data storage pk-utility: {Settings:{CP:{Set:{Sound:1b}}}} run tellraw @s [{"text":"   - CPを設定した際のSound","font":"uniform"},{"text":"'                            ","color":"dark_gray"},{"text":"⦿","color":"green"},{"text":"  "},{"text":" ◯ ","color":"gray","clickEvent":{"action":"run_command","value":"/function pk-utility:settings/cp/set/sound/0"}}]
execute unless data storage pk-utility: {Settings:{CP:{Set:{Sound:1b}}}} run tellraw @s [{"text":"   - CPを設定した際のSound","font":"uniform"},{"text":"'                           ","color":"dark_gray"},{"text":" ◯ ","color":"gray","clickEvent":{"action":"run_command","value":"/function pk-utility:settings/cp/set/sound/1"}},{"text":"  "},{"text":"⦿","color":"red"}]

execute if data storage pk-utility: {Settings:{CP:{Set:{Particle:1b}}}} run tellraw @s [{"text":"   - CPを設定した際のParticle","font":"uniform"},{"text":"                          ","color":"dark_gray"},{"text":"⦿","color":"green"},{"text":"  "},{"text":" ◯ ","color":"gray","clickEvent":{"action":"run_command","value":"/function pk-utility:settings/cp/set/particle/0"}}]
execute unless data storage pk-utility: {Settings:{CP:{Set:{Particle:1b}}}} run tellraw @s [{"text":"   - CPを設定した際のParticle","font":"uniform"},{"text":"                         ","color":"dark_gray"},{"text":" ◯ ","color":"gray","clickEvent":{"action":"run_command","value":"/function pk-utility:settings/cp/set/particle/1"}},{"text":"  "},{"text":"⦿","color":"red"}]

execute if data storage pk-utility: {Settings:{CP:{Set:{Message:1b}}}} run tellraw @s [{"text":"   - CPを設定した際のMessage","font":"uniform"},{"text":"'                          ","color":"dark_gray"},{"text":"⦿","color":"green"},{"text":"  "},{"text":" ◯ ","color":"gray","clickEvent":{"action":"run_command","value":"/function pk-utility:settings/cp/set/message/0"}}]
execute unless data storage pk-utility: {Settings:{CP:{Set:{Message:1b}}}} run tellraw @s [{"text":"   - CPを設定した際のMessage","font":"uniform"},{"text":"'                         ","color":"dark_gray"},{"text":" ◯ ","color":"gray","clickEvent":{"action":"run_command","value":"/function pk-utility:settings/cp/set/message/1"}},{"text":"  "},{"text":"⦿","color":"red"}]

execute if data storage pk-utility: {Settings:{CP:{TP:{Failed-Sound:1b}}}} run tellraw @s [{"text":"   - CPへのTPが失敗した際のSound","font":"uniform"},{"text":",'                     ","color":"dark_gray"},{"text":"⦿","color":"green"},{"text":"  "},{"text":" ◯ ","color":"gray","clickEvent":{"action":"run_command","value":"/function pk-utility:settings/cp/tp/failed-sound/0"}}]
execute unless data storage pk-utility: {Settings:{CP:{TP:{Failed-Sound:1b}}}} run tellraw @s [{"text":"   - CPへのTPが失敗した際のSound","font":"uniform"},{"text":",'                    ","color":"dark_gray"},{"text":" ◯ ","color":"gray","clickEvent":{"action":"run_command","value":"/function pk-utility:settings/cp/tp/failed-sound/1"}},{"text":"  "},{"text":"⦿","color":"red"}]

execute if data storage pk-utility: {Settings:{TA:{Sound:1b}}} run tellraw @s [{"text":"   - TAを開始・終了した際のSound","font":"uniform"},{"text":",                     ","color":"dark_gray"},{"text":"⦿","color":"green"},{"text":"  "},{"text":" ◯ ","color":"gray","clickEvent":{"action":"run_command","value":"/function pk-utility:settings/ta/sound/0"}}]
execute unless data storage pk-utility: {Settings:{TA:{Sound:1b}}} run tellraw @s [{"text":"   - TAを開始・終了した際のSound","font":"uniform"},{"text":",                    ","color":"dark_gray"},{"text":" ◯ ","color":"gray","clickEvent":{"action":"run_command","value":"/function pk-utility:settings/ta/sound/1"}},{"text":"  "},{"text":"⦿","color":"red"}]

execute if data storage pk-utility: {Settings:{CP:{Sponge:{Sound:1b}}}} run tellraw @s [{"text":"   - スポンジを踏み、CPへ戻された際のSound","font":"uniform"},{"text":"'          ","color":"dark_gray"},{"text":"⦿","color":"green"},{"text":"  "},{"text":" ◯ ","color":"gray","clickEvent":{"action":"run_command","value":"/function pk-utility:settings/cp/sponge/sound/0"}}]
execute unless data storage pk-utility: {Settings:{CP:{Sponge:{Sound:1b}}}} run tellraw @s [{"text":"   - スポンジを踏み、CPへ戻された際のSound","font":"uniform"},{"text":"'         ","color":"dark_gray"},{"text":" ◯ ","color":"gray","clickEvent":{"action":"run_command","value":"/function pk-utility:settings/cp/sponge/sound/1"}},{"text":"  "},{"text":"⦿","color":"red"}]